# 🔐 Credenziali del Service Account Google
[gcp_service_account]
type = "service_account"
project_id = "mio-progetto-id"
private_key_id = "abc123456789..."
private_key = "-----BEGIN PRIVATE KEY-----\nMIIBVgIBADANBgkq...\n-----END PRIVATE KEY-----\n"
client_email = "service-account@mio-progetto.iam.gserviceaccount.com"
client_id = "123456789012345678901"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/service-account%40mio-progetto.iam.gserviceaccount.com"

# 📄 Link al tuo Google Sheet (così non serve scriverlo nel codice)
[sheet]
url = "https://docs.google.com/spreadsheets/d/1_mwlW5sklv-D_992aWC--S3nfg-OJNOs4Nn2RZr8IPE/edit?gid=560544700#gid=560544700"
